#Chapter 08. 이미지를 위한 인공 신경망
##합성곱 신경망(convolution neural network;CNN)의 구성 요소
###합성곱(convolution)
###케라스 합성곱 층

In [1]:
from tensorflow import keras

keras.layers.Conv2D(
    10,
    kernel_size=(3, 3),
    activation='relu'
)

**패딩과 스트라이드**  
세임 패딩(same padding)  
밸리드 패딩(valid padding)

In [2]:
keras.layers.Conv2D(
    10,
    kernel_size=(3, 3),
    activation='relu',
    padding='same'
)

스트라이드(stride)

In [4]:
keras.layers.Conv2D(
    10,
    kernel_size=(3, 3),
    activation='relu',
    padding='same',
    strides=1
)

**풀링(pooling)**  
최대 풀링(max pooling)  
평균 풀링(average pooling)

In [6]:
keras.layers.MaxPooling2D(2)

In [8]:
keras.layers.MaxPooling2D(
    2,
    strides=2,
    padding='valid'
)

###합성곱 신경망의 전체 구조
**컬러 이미지를 사용한 합성곱**

확인 문제 2

In [82]:
import numpy as np

input_layer = np.array(
    [3,0,9,1,2,5,1,2,0,7,8,2,4,1,3,2,1,5,3,6,4,1,6,2,7]
).reshape(5, 5)
kernal_layer = np.array(
    [2,0,1,2,0,1,2,0,1]
).reshape(3, 3)

In [78]:
output_layer = np.array([[0]*3, [0]*3, [0]*3])

In [83]:
for i in range(3):
  for j in range(3):
    output_layer[i, j] = np.sum(
        input_layer[(0+i):(3+i), (0+j):(3+j)] * kernel_layer
    )
print(output_layer)

[[47  8 42]
 [41 12 38]
 [43 14 46]]


확인 문제 3

In [75]:
input_layer = np.array(
    [6,9,7,10,2,6,10,2,1,2,2,1,6,4,9,8,6,9,4,0,3,7,5,1,8,8,0,8,1,3,2,3]
).reshape(4, 4, 2)

In [61]:
output_layer = np.array(
    [
        [
          [0] * 2,
          [0] * 2
        ],[
          [0] * 2,
          [0] * 2
        ]
    ]
)

In [76]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      output_layer[i, j, k] = np.max(
        input_layer[(0+i*2):(2+i*2), (0+j*2):(2+j*2), k]
    )
print(output_layer)

[[[ 7 10]
  [10  8]]

 [[ 8  9]
  [ 5  7]]]
